// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RATA.Shared.Services;

#nullable disable

namespace RATA.Shared.Migrations
{
    [DbContext(typeof(TenantDatabase))]
    [Migration("20241006123455_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("RATA.Shared.Models.Tenant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Advance")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RentedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VacatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TenantSet");
                });

            modelBuilder.Entity("RATA.Shared.Models.TenantMaintenance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Maintenance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WaterBill")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TenantMaintenanceSet");
                });
#pragma warning restore 612, 618
        }
    }
}
